services:
  phoenix:
    image: arizephoenix/phoenix:version-20.4.0
    ports:
      - "6006:6006"
      - "4317:4317"
    environment:
      PHOENIX_WORKING_DIR: /mnt/data
      PHOENIX_ALLOW_EXTERNAL_RESOURCES: "false"
    volumes:
      - phoenix_data:/mnt/data

volumes:
  phoenix_data:
